# Generated by Django 4.0.3 on 2022-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTest',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_date', models.DateField()),
                ('tests', models.CharField(max_length=25)),
                ('booking_status', models.IntegerField()),
            ],
            options={
                'db_table': 'booked_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=191)),
                ('test_cost', models.CharField(max_length=191)),
                ('lab_test_image', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'lab_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255, unique=True)),
                ('patient_email', models.CharField(max_length=255, unique=True)),
                ('patient_password', models.CharField(max_length=255)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=45, null=True)),
                ('patient_status', models.IntegerField(blank=True, null=True)),
                ('patient_phone_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
    ]
