# Generated by Django 4.0.3 on 2022-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_bookedtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pat_id', models.IntegerField(blank=True, null=True)),
                ('b_date', models.DateTimeField(blank=True, null=True)),
                ('booking_status', models.IntegerField(blank=True, null=True)),
                ('test_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
    ]
