# Generated by Django 4.0.3 on 2022-04-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_bookedtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTest',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_date', models.DateTimeField()),
                ('tests', models.CharField(max_length=25)),
                ('booking_status', models.IntegerField()),
            ],
            options={
                'db_table': 'booked_test',
                'managed': False,
            },
        ),
    ]
