# Generated by Django 4.0.3 on 2022-04-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_bookedtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedTest',
        ),
    ]
