# Generated by Django 4.0.3 on 2022-04-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_bookedtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTest',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_date', models.DateTimeField()),
                ('tests', models.CharField(max_length=25)),
                ('booking_status', models.IntegerField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.patients')),
            ],
        ),
    ]
