# Generated by Django 4.0.3 on 2022-04-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_bookedtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedtest',
            name='booking_status',
            field=models.CharField(max_length=40),
        ),
    ]
